name: Update ppmain
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: Update ppmain periodically
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: |
          python scrape.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ppmain.csv
          git commit -m "Updated pp on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin main || echo "No Changes to Commit"